# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gradle-to-capistrano 0.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "gradle-to-capistrano"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Marcos Sousa"]
  s.date = "2015-01-05"
  s.description = "This extension should be used to run gradle commands on gradle based projects. The artifacts generated will be compreessed and copied to the server"
  s.email = "falecomigo@marcossousa.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "gradle-to-capistrano.gemspec",
    "lib/capistrano/recipes/deploy/strategy/gradle_build.rb",
    "lib/gradle-to-capistrano.rb",
    "test/helper.rb",
    "test/test_gradle-to-capistrano.rb"
  ]
  s.homepage = "http://github.com/marcossousa/gradle-to-capistrano"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Capistrano recipe to run gradle commands to generate deployable artifacts"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

